thinknimble/tn-models-fp

.changeset/fresh-apricots-hug.md
.github/workflows/main.yml
src/api.test.ts
src/api.ts

- Add pagination parameter to createPaginatedServiceCall resulting callback
- Release 1.2.0
- Rm gh action on push for pushes on any branch. Restrict it to only main

Change createPaginatedServiceCall to make its associated callback ask for a pagination object

---

src/api.test.ts
src/utils.test.ts
src/utils/zod.ts

- add initial work and tests for zod recursive util.
Addresses core functionality of #29 
- `default`
- `catch` 
- `refine` or any of the other `ZodEffects`
- `pipe`

Add zod shape utilities to work with snake case and still take adv of zod utilities

---

.changeset/sweet-kangaroos-speak.md
src/utils/api.ts
src/utils/utils.test.ts

- Fix wrong zod on fromApi util
- Add basic tests for fromApi and toApi

Fix `fromApi` using the wrong zod to parse response warning

---

.changeset/beige-lamps-tie.md
src/api/api.test.ts
src/api/create-api.ts

- rework types to allow skipping models
- add extra overload for createApi so we address the case where no models are passed
- add tests both for TS and runtime so that we make sure this change does not break current behaviour
- remove a bunch of generic types that were assumed from models object, now we do their types only when we know that they're being passed
2.2.0 Release
Closes #13

Allow skipping models on `createApi`

---

.changeset/dry-dogs-glow.md
README.md
package.json
pnpm-lock.yaml
src/api/api.test.ts
src/api/create-api.ts
src/api/create-paginated-call.ts
src/api/types.ts
src/global.d.ts

~- I am yet to be able to find a way to improve this, it does not work properly as it is we need the  user to cast as const whatever they pass which is BS.~
This might be ready I want to ponder a little more on whether this is a good approach or not. Probably will do a release with this, check it out whether it is more a pain than a solution and if that is so I would revert it.
Would: 
- Closes #45

Warn users if their uris are not slash-ended

---

.changeset/twenty-months-share.md
src/utils/api.ts

I missed a check to rule out the possibility of a variable being null.
`null` is considered of type `object` so my filter (`typeof obj === 'object'`) was not enough to discard `null` as a possibility.
Closes #65

Hotfix `objectToCamelCaseArr` crashing on null values

---

.changeset/slow-books-jam.md
src/api/create-api.ts
src/api/tests/create-api.test.ts
src/api/tests/mocks.ts
src/collection-manager/collection-manager.test.ts
src/utils/api/api.ts
src/utils/zod/zod.ts

- Add some brand return type fixes
- Infer id type from entity shape rather than assuming string

Infer `id` from entity shape rather than assuming `string`

---

.changeset/sharp-kangaroos-breathe.md
README.md
src/api/create-api.ts
src/api/tests/create-api.test.ts
src/utils/zod/zod.ts

`create` method now defaults its input based on `models.entity`

---

.changeset/spotty-boats-heal.md
src/api/create-api.ts
src/api/create-paginated-call.ts
src/api/tests/create-api.test.ts
src/api/tests/create-custom-call.test.ts
src/api/tests/create-paginated-call.test.ts
src/api/tests/mocks.ts
src/api/types.ts
src/utils/api/api.ts
src/utils/api/types.ts
src/utils/filters.ts
src/utils/tests/create-api-utils.test.ts
src/utils/zod/types.ts

- GetInferredFromRaw no longer infers readonly brands as such, instead it yields the inner type instead

Remove readonly brand inference in GetInferredFromRaw util

---

.changeset/early-actors-fail.md
src/api/tests/create-custom-call.test.ts
src/api/types.ts

- allow output shape in custom calls to be of type zod array thus matching the same signature for create custom service call (ths probably needs to be unified across the library so that we avoid these issues)
- Remove some mocked responses that were not being consumed and thus they were leaking to other tests

createCustomServiceCall - Allow outputShape to be array

---

.changeset/tender-mangos-switch.md
src/index.ts

Closes #124 
Ty @villagrat for catching this!

Fix : Move `readonly` fn to right export. It was exporting as type 

---

.changeset/pretty-poets-eat.md
src/api/create-api.ts
src/api/tests/create-api.test.ts
src/utils/api/api.ts
src/utils/tests/create-api-utils.test.ts
src/utils/zod/zod.ts

- Change the way `z.ZodBranded` is being checked. For some reason (which I am still not sure) the brand class type was removed at some point of the processing of the zod instance. This worked fine in React but in environments like Vue and RunJS this problem arose.
Closes #132

Fix `readonly` brand not being stripped from `create` shape override

---

.changeset/smart-gorillas-stare.md
src/api/create-api.ts
src/api/tests/create-api.test.ts

- allow users to opt out of built in methods trailing slash
- Improve type layer around the trailing slash so that if we choose this option the trailing slash should no longer be type-checked

Add flag to allow to call apis without a trailing slash.

---

.changeset/thirty-phones-talk.md
src/api/tests/create-api.test.ts
src/api/tests/create-paginated-call.test.ts
src/utils/api/api.ts
src/utils/pagination.ts
src/utils/response.ts
src/utils/tests/response.test.ts
src/utils/zod/zod.ts

Closes #143 
- Add passthrough to parseResponse so that responses don't get their fields obfuscated.
- Add tests to both regular calls and paginated calls (which use a slightly different approach for parsing responses)
Any extra fields that come from responses will now be allowed through the zod parsing.
This creates a minor inconsistency with paginated calls and regular calls. Given that paginated calls use a custom zod (managed by this library) we are also camelcasing the unknown keys. Whereas regular calls will have the fields trickled as snake cased (since their zod is not taking them into account)

Stop obfuscation of extra fields from responses.

---

.changeset/rude-ducks-rule.md
package.json

Closes #148 
From now own, the `tn-models-fp` package will become deprecated in favor of continuing with the versioning in `tn-models` instead. Starting from 2.0.0

Move to @thinknimble/tn-models

---

src/api/create-api.ts
src/api/create-paginated-call.ts
src/api/tests/create-api.test.ts
src/api/tests/create-paginated-call.test.ts
src/api/types.ts
src/utils/zod/types.ts

Remove brand type from outputs, Fix misleading type error on createApi when entity is in wrong format

---

.changeset/hot-waves-deliver.md
package.json
src/api/tests/create-api.test.ts
src/api/tests/create-custom-call.test.ts
src/collection-manager/collection-manager.test.ts
src/utils/api/api.ts
src/utils/filters.ts
src/utils/tests/create-api-utils.test.ts
src/utils/tests/response.test.ts
src/utils/zod/zod.ts

- `instanceof` is causing v weird issues in some node runtimes. seems like the bundling of this js feature is not consistent across different nodejs environments. IG: works in react, but doesn't work properly in Vue / RunJS
- Replaced `instanceof` with a sort of naive implementation that relies on typeNames of the different zod classes (since this is what we were using it for, to discriminate certain zodtypes at runtime).
- Add a dev:watch to rebuild on file change in case we want to use this for debugging purposes
- EXTRA FIX - Rm all objectToSnakeCase and objectToCamelCase that don't properly handle arrays. Use our own implementations that do recursive snake casing of objects.  TODO: move to tn-utils
Closes #152

Fix issue with `instanceof` operator yielding inconsistent results when using it in different runtimes

---

src/utils/zod/zod.ts

Previous solution appeared to work at first sight but when using this in a monorepo something about the `.name` was not bundled correctly giving off results

Change way we referto zod type names to an official export

---

.changeset/ten-fireants-drop.md
src/index.ts

Add a couple of exports that are used by the library internally to infer types. Without these exports type inference could lead to bad types such as  `{ [x:string] : any }` Which are very annoying to deal with as a lib user

Add more exports

---

.changeset/slimy-hairs-jog.md
src/api/create-api.ts
src/api/tests/create-api.test.ts

I believe this is related with the following:
Closes #113 
Just checked, this seems not to be a problem anymore but it may be introduce an improvement so will close it nonetheless with this PR

Remove `filters` param if there was no filters declared

---

src/collection-manager/collection-manager.test.ts
src/collection-manager/index.ts

It appears filters need a specific syntax to be updated, I've also returned the filters object

Added tests for the filters

---

.changeset/green-shrimps-return.md
src/api/create-api.ts
src/api/tests/create-api.test.ts

Add missing `fromApi` call to result of `update` built-in

Fix issue with update not returning camel cased.

---

.changeset/sweet-fishes-march.md
src/api/create-api.ts
src/api/create-paginated-call.ts
src/api/tests/create-custom-call.test.ts
src/utils/api/api.ts
src/utils/filters.ts
src/utils/tests/filters.test.ts

Closes #173 
These are internal for the library but we can potentially lift it to users so they can control this
- Add chance to define a custom parser
- Provide a default parser for convenience

Allow custom filters parser. Add a default filter parser which addresses arrays by joining elements into string

---

.changeset/curly-geese-kiss.md
src/api/create-custom-call.ts
src/api/tests/create-custom-call.test.ts
src/api/types.ts
src/utils/zod/types.ts

- Fix issue where using shapes with `readonly` fields in custom service calls would break `createApi` resulting custom call type.

Fix issue with readonly fields breaking custom service calls when they're added to ouput shapes

---

.changeset/wise-berries-worry.md
src/api/create-api.ts
src/api/create-paginated-call.ts
src/utils/api/api.ts
src/utils/filters.ts
src/utils/response.ts

- wrap in try-catch all parse calls so that errors don't go unnoticed when toApi or other parsing locations are called
- Allow users to mute zod warnings which could potentially be too bloating. This can be controlled at `createApi` level as an option with `disableLoggingWarning`

Allow the possibility of disabling logs in

---

.changeset/strange-ladybugs-press.md
src/api/tests/create-custom-call.test.ts
src/api/types.ts
src/utils/zod/types.ts

Closes #182 
Add unwrap recursive to the output shape type resolution of the custom service calls.

Fix issue with `outputShape` not properly unwrapping branded fields.

---

.changeset/kind-zebras-remain.md
.changeset/pre.json
.changeset/pretty-tigers-attend.md
CHANGELOG.md
package.json
src/utils/zod/types.ts

Readonly is only used for prevent showing fields for user when they do updates. There's not much point in trickling the readonly in typescript for the output. This could cause dumb type errors for the user.

Chore: Remove readonly fields from the output of custom calls causing errors on users.
